server:
  port: 2023

spring:
  application:
    name: alibaba-dubbo-provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.140:3306/master0
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.140:8848

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.liang.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    # dubbo 高速序列化工具
    serialization: kryo
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://192.168.11.140:8848
  cloud:
    subscribed-services: ""
  provider:
    loadbalance: roundrobin

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.liang.mapper: debug