spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 熔断限流
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

# 开启 Feign 对 Sentinel 的支持
feign:
  sentinel:
    enabled: true

server:
  port: 8090

management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"