spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.129:8848
    # 熔断限流
    sentinel:
      transport:
        dashboard: 192.168.3.129:8085

# 开启 Feign 对 Sentinel 的支持
feign:
  sentinel:
    enabled: true

server:
  port: 8090

management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"