spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.129:8848

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'