spring:
  application:
    name: dubbo-consumer
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: com.liang.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.3.129:8848
server:
  port: 8081